apiVersion: v1
kind: Service
metadata:
  name: cibus-api
  namespace: production
spec:
  selector:
    app: cibus-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
